name: Aqar Real Estate Pipeline

on:
  schedule:
    # Run every 3 days at 1:00 AM UTC
    - cron: '0 1 */3 * *'
  workflow_dispatch:
    inputs:
      reason:
        description: 'Reason for manual pipeline run'
        required: false
        default: 'Manual execution of Aqar real estate pipeline'

jobs:
  run_aqar_real_estate_pipeline:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code for reference
      uses: actions/checkout@v3
      
    - name: Run Aqar real estate pipeline on VPS
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.VPS_HOST }}
        username: ${{ secrets.VPS_USERNAME }}
        key: ${{ secrets.VPS_SSH_KEY }}
        script: |
          # Navigate to the project directory
          cd /zyte_scraper
          
          # Pull latest code including the Aqar real estate pipeline
          git pull
          
          # Make the pipeline executable (if needed)
          chmod +x aqar_real_estate_pipeline.py
          
          # Install required packages
          echo "Installing required packages..."
          sudo apt-get update
          sudo apt-get install -y python3-pip python3-venv
          
          # Verify Python installation
          echo "Checking Python installation..."
          which python3
          python3 --version
          
          # Remove existing venv if it exists but is incomplete
          if [ -d "venv" ]; then
            echo "Removing existing venv directory..."
            rm -rf venv
          fi
          
          # Create virtual environment
          echo "Creating virtual environment..."
          python3 -m venv venv
          
          # Verify venv creation
          if [ ! -f "venv/bin/activate" ]; then
            echo "Virtual environment creation failed!"
            ls -la venv
            exit 1
          fi
          
          # Activate virtual environment
          echo "Activating virtual environment..."
          source venv/bin/activate
          
          # Verify we're in the virtual environment
          echo "Python path after activation:"
          which python
          
          # Install or update dependencies
          echo "Installing dependencies..."
          python -m pip install --upgrade pip
          
          # Check if requirements.txt exists
          if [ -f "requirements.txt" ]; then
            pip install -r requirements.txt
          else
            echo "Warning: requirements.txt not found. Installing essential packages..."
            pip install scrapy google-cloud-storage psycopg2-binary
          fi
          
          # Execute the Aqar real estate pipeline
          echo "Running pipeline..."
          python aqar_real_estate_pipeline.py
          
          # Deactivate virtual environment
          deactivate
