name: Aqar Real Estate Pipeline

on:
  schedule:
    # Run every 3 days at 1:00 AM UTC
    - cron: '0 1 */3 * *'
  workflow_dispatch:
    inputs:
      reason:
        description: 'Reason for manual pipeline run'
        required: false
        default: 'Manual execution of Aqar real estate pipeline'

jobs:
  run_aqar_real_estate_pipeline:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code for reference
      uses: actions/checkout@v3
      
    - name: Run Aqar real estate pipeline on VPS
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.VPS_HOST }}
        username: ${{ secrets.VPS_USERNAME }}
        key: ${{ secrets.VPS_SSH_KEY }}
        script: |
          # Navigate to the project directory
          cd /zyte_scraper
          
          # Pull latest code including the Aqar real estate pipeline
          git pull
          
          # Make the pipeline executable (if needed)
          chmod +x aqar_real_estate_pipeline.py
          
          # Install required packages first
          echo "Installing required packages..."
          sudo apt-get update
          # Determine Python version and install appropriate venv package
          PYTHON_VERSION=$(python3 --version | cut -d' ' -f2 | cut -d'.' -f1-2)
          sudo apt-get install -y python3-venv
          
          # Create virtual environment if it doesn't exist
          if [ ! -d "venv" ]; then
            echo "Creating virtual environment..."
            python3 -m venv venv
          fi
          
          # Activate virtual environment
          echo "Activating virtual environment..."
          source venv/bin/activate
          
          # Verify we're in the virtual environment
          which python
          python --version
          
          # Install or update dependencies
          echo "Installing dependencies..."
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          
          # Execute the Aqar real estate pipeline
          echo "Running pipeline..."
          python aqar_real_estate_pipeline.py
          
          # Deactivate virtual environment
          deactivate