name: Deploy Traffic API to VPS

on:
  # push:
  #   branches: [ main ]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Deploy to VPS (docker-compose)
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USERNAME }}
          key: ${{ secrets.VPS_SSH_KEY }}
          script: |
            set -e

            # Check if docker-compose is installed
            if ! command -v docker-compose &> /dev/null; then
                echo "docker-compose not found. Installing..."
                sudo curl -L "https://github.com/docker/compose/releases/download/v2.28.0/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
                sudo chmod +x /usr/local/bin/docker-compose
            fi

            # Check if traffic_api folder exists
            if [ -d "/zyte_scraper/traffic_api" ]; then
                cd /zyte_scraper/traffic_api
                git pull
                cd traffic_api
            else
                cd /zyte_scraper
                git clone https://github.com/osamalzabidi/zyte_scraper.git traffic_api
                cd /zyte_scraper/traffic_api/traffic_api
            fi

            # Build and run Docker containers
            docker-compose down || true
            docker-compose build --no-cache
            docker-compose up -d

