name: Deploy Traffic API in GitHub Actions

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Docker
        uses: docker/setup-buildx-action@v2

      - name: Build Docker image
        run: docker build -t traffic-api .

      - name: Run API in Docker
        run: |
          docker run -d -p 8000:8000 --name traffic-api traffic-api

      - name: Install ngrok
        run: |
          curl -s https://ngrok-agent.s3.amazonaws.com/ngrok.asc | sudo tee /etc/apt/trusted.gpg.d/ngrok.asc >/dev/null
          echo "deb https://ngrok-agent.s3.amazonaws.com buster main" | sudo tee /etc/apt/sources.list.d/ngrok.list
          sudo apt update && sudo apt install ngrok -y

      - name: Start ngrok and get public URL
        id: ngrok
        run: |
          ngrok http 8000 --log=stdout > ngrok.log &
          sleep 5
          URL=$(curl -s http://127.0.0.1:4040/api/tunnels | jq -r '.tunnels[0].public_url')
          echo "ngrok_url=$URL" >> $GITHUB_OUTPUT

      - name: Show test URL
        run: echo "API is live at ${{ steps.ngrok.outputs.ngrok_url }}"
